### PR TITLE
Fix compile with DBString & Add Vocabulary Widget

### PR DESCRIPTION
**Pull request by Ghabry**
~~_FIXME:
- Vocabulary UI disabled for now - This code is too much work to fix. Should be directly rewritten to WidgetHelper (Also much less code dupe this way)
- Linker error when ReaderUtil is invoked_~~ SOLVED

@fmatthew5876 
I get a very strange linker error, any idea what this means?

```cpp
/bin/ld: libEasyRPG_Editor.a(project.cpp.o): en la función `Project::load(QDir const&)':
project.cpp:(.text+0x717): referencia a `lcf::ReaderUtil::DetectEncoding[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >)' sin definir
/bin/ld: project.cpp:(.text+0x7d6): referencia a `lcf::ReaderUtil::Recode[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >)' sin definir
```

### CODE REVIEW

**Comment by Ghabry** [comment]
And on the GNU/Linux bot I see another new linker error related to empty buf of DBString.

I'm lost here what the cause is so somebody else has to fix the rest please.

**Comment by fmatthew5876** [comment]
I was able to make this PR build against https://github.com/EasyRPG/liblcf/pull/400 with this patch

```
diff --git a/src/ui/main_window.cpp b/src/ui/main_window.cpp
index 15c55bd..d3776a8 100644
--- a/src/ui/main_window.cpp
+++ b/src/ui/main_window.cpp
@@ -706,7 +706,7 @@ QGraphicsView *MainWindow::getView(int id)
                for (unsigned int i = 0; i < core().project()->treeMap().maps.size();i++)
                        if (core().project()->treeMap().maps[i].ID == id)
                        {
-                               mapName = core().project()->treeMap().maps[i].name;
+                               mapName = ToString(core().project()->treeMap().maps[i].name);
                                break;
                        }
                ui->tabMap->addTab(view,
```

**Comment by Ghabry** [comment]
I completely redesigned the Vocabulary UI and deleted 99% of the legacy code.

The entire Widget is now basicly this:

(Note: ``bind`` and ``connect`` can't be merged. Usually they are splitted:connect is in the constructor, bind is for updating values)

```cpp
	ui->setupUi(this);

	lcf::rpg::ForEachString(*terms, [&](auto& val, const lcf::ContextStructBase<lcf::rpg::Terms>& ctx) {
		auto* line = this->findChild<QLineEdit*>(ToQString(ctx.name));
		if (!line) {
			std::cerr << "BUG: Vocabulary: No widget found for " << ctx.name << "\n";
			return;
		}

		LcfWidgetBinding::connect(this, line);
		LcfWidgetBinding::bind(line, val);
	});
```

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
jenkins: test this please

**Comment by Ghabry** [comment]
jenkins: test this please

**Comment by Ghabry** [comment]
temporary workaround: Switched to Clang. No linker error (but ASAN catches it: https://bugs.llvm.org/show_bug.cgi?id=28391 )

**Pull request merged**
