### PR TITLE
enable caching for the search dialog

### PR DESCRIPTION
**Pull request by punkkeks**
Enable simple caching of parsed maps in the searchdialog. This will decrease the search time drastically. You also can disable this in the mainwindow with a tickbox.

### CODE REVIEW

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by punkkeks** [comment]
I would like to see caching, but I think you should merge #90 first, and after that I will try to implement this again, or you could do it as well ;)

**Comment by Ghabry** [comment]
Well one of you has to rebase on upstream and resolve the conflicts after one PR is merged.

**Comment by Zegeri** [comment]
I'll do the rebase.

**Comment by Ghabry** [comment]
@punkkeks  The mail address of your commits doesn't match with your account mail. Just for information, I don't care.

**Comment by punkkeks** [comment]
I know @Ghabry , I have a catch-all mailbox, so you can also send a mail ghabry@cookiesoft.de if you want  ;)

**Comment by Ghabry** [comment]
I do it in a similiar way @punkkeks (different mail for any website). I just added the additional mail addresses to my github account to get that icon displayed next to all my commits :D

**Pull request merged**
