### PR TITLE
CMake: Build macOS app bundle

### LINKED ISSUE #141: macOS: Add AppBundle support
The CMakeLists lacks App bundle support.
Also there is no suitable icon and no suitable plist file.

@tyrone-sudeium can you help? :)

For "macqtdeploy" see https://stackoverflow.com/questions/51556088/cmake-copy-dependencies-to-executable-output-path/51569345 (tested it, works)

### PR DESCRIPTION
**Pull request by tyrone-sudeium**
Adds `.app` bundle support for macOS builds.

TODO: Update the app icon. Right now it's using the Player icon, since I couldn't find an SVG for the Editor icon. @Ghabry do we have one?

Fixes #141

### CODE REVIEW

**Comment by Ghabry** [comment]
A made a quick test and it works excellent. Thanks! Only have to update Jenkins now :).

Archive size is 55 MB, can be reduced later by skipping unnecessary frameworks, so doesn't really matter.

We only have a low quality icon in the Windows ICO file: https://github.com/EasyRPG/Editor-Qt/tree/master/resources/app
@fdelapena is there any better version of the editor logo?

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by tyrone-sudeium** [comment]
On the unnecessary frameworks, I initially tried to forgo using `macdeployqt` entirely and just rely on cmake's `fixup_bundle` stuff, since that will detect just the frameworks that are being referenced and copy them across. Unfortunately, Qt does weird stuff, such as needing that `qt.conf` in the bundle, as well as some subset of the `PlugIns` being required, both of which `fixup_bundle` can't detect. I'm not sure how to make `macdeployqt` less eager. Other projects (such as OBS) manually copy across the stuff they need into the bundle using a bespoke script.

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
On Windows I switched to a static build because this makes the linking much easier (you cant mix DLLs with libs when the C++ runtime disagrees). Also no need for the qt deploy tool. Maybe I will do the same for MacOS later...

**Comment by Ghabry** [comment]
Jenkins: test this please

**Pull request merged**
