### PR TITLE
Improve project importing and event page

### PR DESCRIPTION
**Pull request by Zegeri**
* I propose dropping support for Qt4 builds. In fact, the current editor-qt won't compile with Qt4 since 2014 because we use some Qt5-only modules like QMediaPlayer (884da676).
* The commands of the event page should look now more familiar to the usual RPG Maker user.

captura de pantalla_2016-04-28_20-22-04

[This is how it currently looks like this](https://cloud.githubusercontent.com/assets/4390703/14901595/7c6df896-0d96-11e6-9a0e-793631446719.png). There are still some missing commands related to battle and the commands introduced by RPG2k3 1.11.
* To fix the issue of XYZ images of existing RPG Maker projects, we have two options, add support for XYZ reading on the go or convert them once when importing files. I've decided to go the latter way because it's much easier. Full XYZ support could be added in the future.
captura de pantalla_2016-04-28_23-22-22
* Not many RPG Maker users will be interested in the line number of some event command, but it's useful for EasyRPG Player developpers to debug some games.
captura de pantalla_2016-04-28_23-40-11

### CODE REVIEW

**Comment by Zegeri** [comment]
I found some issues, please, don't merge yet.

**Comment by Ghabry** [comment]
Awesome, 100 :+1: for you. I have a reason now to revive the Editor-Qt (PR) builder for Windows :D.

**Comment by fdelapena** [comment]
jenkins: retest this please <3

**Comment by Zegeri** [comment]
Issues resolved and rebased to the upstream HEAD.

**Comment by Ghabry** [comment]
Teleport parses wrong
unbenannt

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by MarianoGnu** [comment]
Great work, but i want to know, what file is the "Line: 441" tooltip refered to?

**Comment by Zegeri** [comment]
It's its index in the list of command of the current event page. I added it for debugging purposes.

**Pull request merged**
