### PR TITLE
Refactor project loading and support legacy (RPG2k/2k3) project load

### PR DESCRIPTION
**Pull request by Ghabry**
Depends on #124

**Don't open any games you care about, the editor will write into the DB/Tree, increment the savecount and could corrupt it due to bugs/crashes**

Wow, this took much longer to write than expected...

The first commit is very complex and touches everything, was more of a "change it until it works" commit, sorry. It attempts to remove some logic from Core and MainWindow and move it into model/Project.
This also allowed to add legacy project loading, encoding detection is supported but not very reliable yet (only reads the Game title) but you can overwrite it with the well-known Encoding= ini entry.
File handling is now with a lovely FileFinder (but much less complex than the one in Player), to support case insensitive file finding.

All direct Data:: member access to liblcf is removed and goes through project() now. Not very useful yet because Data is global but to change this properly we also need to alter this in Player code and liblcf.

Also added XYZ loading.

Still WIP, many things are disabled/broken.

> carstene1ns: editor project feels like a zombie

source

### CODE REVIEW

**Comment by Ghabry** [comment]
Well this is now good enough for loading legacy projects and viewing them in our Editor :).

Still broken are "New Project" and "Import Project"

**Comment by Ghabry** [comment]
Question: Does it make sense currently to fix "New" and "Import"?

The main problem is that we still havn't decided about the editor format is supposed to look. I guess XML has lost by now and JSON is the new candidate, but this needs liblcf support first. :)

**Comment by fdelapena** [comment]
I think a simple *.dat template copy like original editor does could help for quick development tests with native legacy format until the new candidate arrives. Import feature for sure may wait for liblcf imho.

**Comment by Ghabry** [comment]
shall I generate "fresh" XML files for LDB and LMT? Now liblcf chunk names should be quite stable.

**Comment by fdelapena** [comment]
If new project goes with lcf or now, replacing base XML with native lcf would be more stable for free, as the XML (writer?) has some issues yet.
Recovering the 1kb asm exe stub (lost likely by accident) could bring better support for quick project conparison between editors.

**Comment by Ghabry** [comment]
I think the stub was never in editor but in TestGame.
Question is about the copyright of the LDB/LMT file of official editor. Can we just grab it?

**Comment by fdelapena** [comment]
That's a good question, I guess even data in XML and unregistered actor names and data as tradenarks it's still game data but not clear because derived games from RPG Maker are not under the RTP License and RPG Maker license does not mentiin about templates...

**Comment by elsemieni** [comment]
@Ghabry last time I seen rpg_rt stub was in TestGame. At least there was in some git, so I don't think it's lost.

I will seek it when I have some spare time.

**Comment by fdelapena** [comment]
RPG_RT.exe binary stub is here: https://github.com/EasyRPG/TestGame/commit/6af7c2b1da0f49af8a98c104388d9c9e3a07e6d9

About import, it could be disabled until we decide to continue with JSON or fix XML if still worth.

**Comment by Ghabry** [comment]
Well new project and import project work now. I don't like that code though.
The whole MainWindow needs a refactor which is out of scope for this PR, will take days...

So is ready for review/merge now.

**Comment by Ghabry** [comment]
Thanks for merging.
I would in general prefer a more relaxed reviewing process then in Player for now because the editor is still so unfinished many PRs will be gigantic refactors and feature submissions you can't really properly review and: When you break stuff it is not as critical as in Player (except when you damage LCF chunks, but such bugs will be found during review I hope :)). When the Editor is more usable the PRs will also get smaller.
I will also accept any reasonable feature in the editor.

**Pull request merged**
